language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '7'
  - '6'
script:
  - yarn run ci
after_script:
  - bash <(curl -s https://codecov.io/bash)
after_success:
  - yarn run semantic-release
